// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTNGolMundial.UTNGolCoin.Api.Data;

#nullable disable

namespace UTNGolMundial.UTNGolCoin.Api.Migrations
{
    [DbContext(typeof(GolCoinDbContext))]
    partial class GolCoinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UTNGolMundial.UTNGolCoin.Api.Models.Billetera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("billeteras", (string)null);
                });

            modelBuilder.Entity("UTNGolMundial.UTNGolCoin.Api.Models.BonoDiario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaBono")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TransaccionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TransaccionId");

                    b.HasIndex("UsuarioId", "FechaBono")
                        .IsUnique();

                    b.ToTable("bonos_diarios", (string)null);
                });

            modelBuilder.Entity("UTNGolMundial.UTNGolCoin.Api.Models.Prediccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cuota")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaLiquidacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MontoApostado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("PremioPagado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ResultadoOficial")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ResultadoPronosticado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "PartidoId")
                        .IsUnique();

                    b.ToTable("predicciones", (string)null);
                });

            modelBuilder.Entity("UTNGolMundial.UTNGolCoin.Api.Models.Transaccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BilleteraId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PrediccionId")
                        .HasColumnType("int");

                    b.Property<decimal>("SaldoResultante")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BilleteraId");

                    b.HasIndex("PrediccionId");

                    b.ToTable("transacciones", (string)null);
                });

            modelBuilder.Entity("UTNGolMundial.UTNGolCoin.Api.Models.BonoDiario", b =>
                {
                    b.HasOne("UTNGolMundial.UTNGolCoin.Api.Models.Transaccion", "Transaccion")
                        .WithMany()
                        .HasForeignKey("TransaccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("UTNGolMundial.UTNGolCoin.Api.Models.Transaccion", b =>
                {
                    b.HasOne("UTNGolMundial.UTNGolCoin.Api.Models.Billetera", "Billetera")
                        .WithMany("Transacciones")
                        .HasForeignKey("BilleteraId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UTNGolMundial.UTNGolCoin.Api.Models.Prediccion", "Prediccion")
                        .WithMany("Transacciones")
                        .HasForeignKey("PrediccionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Billetera");

                    b.Navigation("Prediccion");
                });

            modelBuilder.Entity("UTNGolMundial.UTNGolCoin.Api.Models.Billetera", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("UTNGolMundial.UTNGolCoin.Api.Models.Prediccion", b =>
                {
                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
